feat: views support external params
dourajs/doura pull request #6
Opened 2023-01-24 15:00 UTC by wangjinyang

2023-01-30 06:09 UTC, liximomo requested changes

2023-01-30 06:09 UTC, liximomo commented on packages/doura/src/core/model.ts
> +            if (hasExternalArgs) {
这个if分支做到 `Object.defineProperty(this.views, viewName, {` 这层会不会对性能更友好点？不需要每次在 getter 内重复判断

2023-01-30 06:09 UTC, liximomo commented on packages/doura/src/core/model.ts
> +  view.dirty = true
dirty 是true的时候，mightChange 再设置 true 其实冗余了。

2023-01-30 06:09 UTC, liximomo commented on packages/doura/src/core/modelOptions.ts
> +      : '555'
555是啥？

2023-01-31 02:44 UTC, liximomo requested changes

2023-01-31 02:44 UTC, liximomo commented on packages/doura/src/core/model.ts
> +          : false
这里直接赋值 getViewResult 是不是更好点？下面就不需要在判断了
```ts
const getValue = hasExternalArgs ?  ... : getViewResult

Object.defineProperty(this.views, viewName, {
          configurable: true,
          enumerable: true,
          get: getValue
}
```

2023-01-31 02:48 UTC, wangjinyang commented on packages/doura/src/core/model.ts
> +          : false
```
            return getViewWithArgsResult
              ? getViewWithArgsResult
              : getViewResult()
```
不行吧？getViewResult()每次都要重新执行一下

2023-01-31 03:11 UTC, merged